### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by HavenOfTheRaven**
I updated dependencies to their latest versions while testing to ensure that nothing broke. I was unable to update three packages due to compilation errors, those being:
 openxr 0.17.1 -> 0.18.0
ash 0.37.3 -> 0.38.0
vulkano 94f50f1 -> b9f3e89

### CODE REVIEW

**Comment by galister** [comment]
Please keep `ash` as is, we need the same version that `vulkano` pulls in.

**Comment by HavenOfTheRaven** [comment]
> Please keep `ash` as is, we need the same version that `vulkano` pulls in.

Vulkano at 94f50f1 uses ash 0.37.3, if you would like I can revert ash to 0.37.2 in Cargo.toml?

**Comment by galister** [comment]
oh nvm then, thanks

**Comment by HavenOfTheRaven** [comment]
Would you like me to fix the compilation errors on vulkano and ash so we can update them?

**Comment by HavenOfTheRaven** [comment]
I decided to take a look at the errors and was easily able to fix them for the new ash and vulkano versions. I then did some testing to confirm everything still worked fine. Currently the only dependency at an earlier version is openxr.

**Comment by HavenOfTheRaven** [comment]
openxr cannot be updated to 0.18.0 since it removes the extx_overlay ExtensionSet, this was added back in with a later commit. Just to clarify ash being updated to 0.38.0 does not create a conflict with Vulkano since Vulkano at b9f3e89 uses ash 0.38.0 as well.

**Comment by galister** [comment]
thanks!

**Comment by HavenOfTheRaven** [comment]
THANK YOU this is one of my first pull requests

**Pull request merged**
